Big update of old orgs
nikitastupin/orgs-data pull request #71
Opened 2024-03-28 19:40 UTC by danilastupin

2024-03-30 11:57 UTC, nikitastupin commented on orgs-data/bugcrowd.tsv
> +https://bugcrowd.com/dropbox	https://github.com/DBMods	3812278
Думаю эта организация не принадлежит Dropbox

2024-03-30 11:58 UTC, nikitastupin commented on orgs-data/chaos.tsv
> +https://bounty.tokopedia.net/rules		https://github.com/tokopedia-devcamp-team6	42794717
Скорее всего эту организацию создали во время соревнования и не будут использовать. Предлагаю не добавлять ее.

2024-03-30 19:19 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/ibb	https://github.com/nginx-modules	7256896
Не уверен, что это принадлежит Nginx. Написано "_Community_ NGINX modules".

2024-03-30 19:21 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/ibb	https://github.com/ngxirc	2318635
Все остальные NGINX тоже выглядят как сторонние разработки

2024-03-30 19:21 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/malwarebytes	https://github.com/axiom-zen-mrrrr	35654084
Не уверен, что это их

2024-03-30 19:24 UTC, nikitastupin commented on orgs-data/hackerone.external_program.tsv
> +https://hackerone.com/mit	https://github.com/mitodl	7918516
На MIT я бы забил, если честно. Не думаю, что они что-то заплатят.

2024-03-30 19:27 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/ibb	https://github.com/NginxID	8537359
Вряд ли принадлежит NGINX

2024-03-30 19:28 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kube-rs	87537212
Не уверен, что эти три принадлежат Kubernetes

2024-03-30 19:29 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kubernetes-native-java	91942500
Не уверен в kubernetes-native-java

2024-03-30 19:30 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kubernetestr	16248116
Не уверен насчет этих двух

2024-03-30 19:31 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/spotify	https://github.com/SpotX-Official	146193339
Скорее всего это поделки коммьюнити

2024-03-30 19:31 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/spotify	https://github.com/spotify-web-api-java	90800172
Не уверен

2024-03-30 19:32 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/tron_dao		https://github.com/webServiceTronapi	125876595
TRON-US может быть, остальные не уверен

2024-03-30 19:33 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/udemy	https://github.com/udemy-jverd	90602978
Кажется, что это курсы отдельного разраба, который на Udemy преподает

2024-03-30 19:35 UTC, nikitastupin commented on orgs-data/diodb.tsv
> +https://www.heroku.com/policy/security	https://github.com/kissaten	8441408
Не их

2024-03-30 19:35 UTC, nikitastupin commented on orgs-data/diodb.tsv
> +https://www.heroku.com/policy/security	https://github.com/heroku2use	36332908
Не их

2024-03-30 19:36 UTC, nikitastupin commented on orgs-data/diodb.tsv
> +https://www.offensive-security.com/bug-bounty-program/	https://github.com/Warlord-Keys	136411161
Домен отличается, почему думаешь, что их?

2024-03-30 19:37 UTC, nikitastupin requested changes
Посмотришь правки выше? В остальном 👍

2024-03-31 07:30 UTC, danilastupin commented on orgs-data/diodb.tsv
> +https://www.offensive-security.com/bug-bounty-program/	https://github.com/Warlord-Keys	136411161
Если перейти по ссылке проги , то будет вот так https://www.offsec.com/bug-bounty-program , поэтому это их

2024-03-31 07:31 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/udemy	https://github.com/udemy-jverd	90602978
Согласен.

2024-03-31 07:33 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/tron_dao		https://github.com/webServiceTronapi	125876595
https://github.com/Ethereumkaykutee -  согласен ,что не валид . Остальные закрыты  и я думаю ,что валидные . Предлагаю пока оставить .

2024-03-31 07:34 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/spotify	https://github.com/spotify-web-api-java	90800172
Почему?

2024-03-31 07:35 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/spotify	https://github.com/SpotX-Official	146193339
Не думал  об этом ,наверное надо убрать.

2024-03-31 07:35 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kubernetestr	16248116
Почему?

2024-03-31 07:44 UTC, danilastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kube-rs	87537212
https://github.com/kube-rs - verifed , не знаю , мне кажется их. https://github.com/charmed-kubernetes я  бы оставил , 
https://github.com/KubernetesCheatsheet - думаю да , убрать

2024-03-31 07:45 UTC, danilastupin commented on orgs-data/hackerone.external_program.tsv
> +https://hackerone.com/mit	https://github.com/mitodl	7918516
Как сам решишь , можно в скрипте добавить в blacklist , а в orgs-data оставить)

2024-03-31 08:27 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/kubernetes	https://github.com/kubernetestr	16248116
- https://github.com/kubernetesbigdataeg - здесь пишут, что это "Community resource"
- https://github.com/kubernetestr - здесь почта kubernetestr@gmail.com которая не в домене Kubernetes

2024-03-31 08:29 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/spotify	https://github.com/spotify-web-api-java	90800172
Это только к https://github.com/spotify-web-api-java относится, если что. Похоже что это разрабатывает один человек и у него еще донаты включены на эту репу. Я не думаю, что коммерческая компания Spotify включала бы донаты для своих опен сорс разработок.

2024-03-31 08:30 UTC, nikitastupin commented on orgs-data/hackerone.tsv
> +https://hackerone.com/tron_dao		https://github.com/webServiceTronapi	125876595
Не знаю даже, здесь https://github.com/TronExpert и здесь https://github.com/tronmask явно домен не принадлежит TRON. Остальные пустые, в принципе можно оставить.

2024-03-31 09:46 UTC, nikitastupin approved these changes
Спасибо! Можно мерджить

2024-03-31 09:46 UTC, merged